# Generated by Django 4.2 on 2023-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("image_file", models.ImageField(upload_to="images/")),
                ("tags", models.ManyToManyField(to="monapplication.tag")),
            ],
        ),
    ]
