# Generated by Django 4.2 on 2023-04-26 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0005_alter_image_image_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="description",),
        migrations.RemoveField(model_name="image", name="image_file",),
        migrations.RemoveField(model_name="image", name="title",),
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(model_name="image", name="tags",),
        migrations.AlterField(
            model_name="image", name="url", field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="image", name="tags", field=models.TextField(blank=True),
        ),
    ]
