# Generated by Django 4.2 on 2023-04-27 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monapplication",
            "0006_remove_image_description_remove_image_image_file_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="created_at",),
        migrations.RemoveField(model_name="image", name="updated_at",),
        migrations.AlterField(
            model_name="image", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="image",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="image", name="url", field=models.CharField(max_length=1024),
        ),
    ]
