# Generated by Django 4.2 on 2023-04-27 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "monapplication",
            "0007_remove_image_created_at_remove_image_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="image", name="tags", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="image", name="url", field=models.URLField(default=""),
        ),
    ]
