# Generated by Django 4.2 on 2023-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monapplication",
            "0008_image_created_at_image_updated_at_alter_image_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="image", name="description", field=models.TextField(blank=True),
        ),
    ]
