# Generated by Django 4.2 on 2023-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0010_alter_image_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="description",),
    ]
