# Generated by Django 4.2 on 2023-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0011_remove_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
