# Generated by Django 4.2 on 2023-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0012_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
