# Generated by Django 4.2 on 2023-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0015_alter_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
