# Generated by Django 4.2 on 2023-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monapplication", "0016_alter_image_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="updated_at",),
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="image", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="image", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="image", name="tags", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="image", name="url", field=models.CharField(max_length=1024),
        ),
    ]
