# Generated by Django 4.2.3 on 2023-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monapplication",
            "0017_remove_image_updated_at_alter_image_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="image", name="description",),
        migrations.AddField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(model_name="image", name="tags",),
        migrations.AddField(
            model_name="image",
            name="descriptions",
            field=models.ManyToManyField(blank=True, to="monapplication.description"),
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(blank=True, to="monapplication.tag"),
        ),
    ]
